/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2019-08-13 15:24:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class template_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html ng-app=\"app\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html;\" charset=\"ISO-8859-1\">\r\n");
      out.write("          <title>PizzOFilia</title>\r\n");
      out.write("\r\n");
      out.write("          <!-- Include CSS files -->\r\n");
      out.write("          <link rel=\"stylesheet\" type=\"text/css\"  href=\"static/css/login.css\">\r\n");
      out.write("          <style>\r\n");
      out.write("            ul{\r\n");
      out.write("              font-family: Lemonade Stand;\r\n");
      out.write("              font-weight: bold;\r\n");
      out.write("              text-shadow: light;\r\n");
      out.write("              width: 550px;\r\n");
      out.write("              list-style-type: none;\r\n");
      out.write("              overflow: hidden;\r\n");
      out.write("              font-size: 30px;\r\n");
      out.write("              margin-top: 25px;\r\n");
      out.write("            }\r\n");
      out.write("            li {\r\n");
      out.write("                float: right;\r\n");
      out.write("\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              li a:visited {\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("                color: white;\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              li a {\r\n");
      out.write("                display: block;\r\n");
      out.write("                color: white;\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                padding-left: 10px;\r\n");
      out.write("                padding-right: 10px;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("              }\r\n");
      out.write("\r\n");
      out.write("              li a:hover {\r\n");
      out.write("                color: skyblue;\r\n");
      out.write("                text-decoration: none;\r\n");
      out.write("              }\r\n");
      out.write("              .logo{\r\n");
      out.write("                height:194px;\r\n");
      out.write("                width:259px;\r\n");
      out.write("                padding-left: 20px;\r\n");
      out.write("                padding-top: 15px;\r\n");
      out.write("              }\r\n");
      out.write("          </style>\r\n");
      out.write("      </head>\r\n");
      out.write("      <body>\r\n");
      out.write("        <div style=\"background: white; margin:-10px; position: fixed;height:100%; width:110%;background-size:auto,cover;\r\n");
      out.write("background-position:top left, center;background-image: linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.6)), url(static/images/la_piazza.jpg);\">\r\n");
      out.write("\r\n");
      out.write("            <div style=\"float:left;\">\r\n");
      out.write("              <img src=\"static/images/logo-3.png\" class=\"logo\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div style=\"float: right; margin-right: 10%;\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                <li ng-hide=\"$localStorage.email\"><a href=\"#/end\">Logout</a></li>\r\n");
      out.write("                <li ng-hide=\"$localStorage.email\"><a href=\"#/login\">Login</a></li>\r\n");
      out.write("                <li ng-hide=\"$localStorage.email\"><a href=\"#/register\">Register</a></li>\r\n");
      out.write("                <li><a href=\"#/\">Home</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- render view dynamically -->\r\n");
      out.write("        <div ng-view>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Include JS files -->\r\n");
      out.write("        <!-- Include angular -->\r\n");
      out.write("        <script src=\"static/js/angular.js\"></script>\r\n");
      out.write("        <script src=\"static/js/angular-route.js\"></script>\r\n");
      out.write("        <script src=\"static/js/angular-cookies.js\"></script>\r\n");
      out.write("        <script src=\"static/js/angular-animate.js\"></script>\r\n");
      out.write("        <script src=\"static/js/ngStorage.min.js\"></script>\r\n");
      out.write("        <!-- Include routing scripts -->\r\n");
      out.write("        <script src=\"static/js/app.js\"></script>\r\n");
      out.write("        <!-- Include services -->\r\n");
      out.write("         <script src=\"static/app-services/order.service.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"static/app-services/user.service.js\"></script>\r\n");
      out.write("        <!-- Include angular controller scripts -->\r\n");
      out.write("        <script src=\"static/home/home.controller.js\"></script>\r\n");
      out.write("        <script src=\"static/login/login.controller.js\"></script>\r\n");
      out.write("        <script src=\"static/register/register.controller.js\"></script>\r\n");
      out.write("         <script src=\"static/order/order.controller.js\"></script>\r\n");
      out.write("         <script src=\"static/editorder/editorder.controller.js\"></script>\r\n");
      out.write("         <script src=\"static/end/end.controller.js\"></script>\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("         app\r\n");
      out.write("         .controller('MainCtrl',function($scope, $localStorage) {\r\n");
      out.write("        \t var vm = function(){\r\n");
      out.write("        \t\t if($localStorage.email){return true;}\r\n");
      out.write("        \t\t else { return; }\r\n");
      out.write("        \t }\r\n");
      out.write("         });\r\n");
      out.write("         </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
