# syntax=docker/dockerfile:1
FROM tomcat:9-jdk8-openjdk

COPY ./war/PizzaWale.war /usr/local/tomcat/webapps/
COPY ./tomcatscript/tomcatscript.sh /

EXPOSE 8080

#RUN apt update && apt install apt-utils -y && apt install socat -y && socat tcp-listen:3306,fork TCP:10.5.0.5:3306 &
#CMD ["apt", "update"]
#CMD ["apt", "install", "apt-utils", "-y"]
#CMD ["apt", "install", "socat", "-y"]
#CMD ["socat", "tcp-listen:3306,fork TCP:10.5.0.5:3306", "&" ]
#CMD ["catalina.sh", "run"]
ENTRYPOINT ["/tomcatscript.sh"]
#ENTRYPOINT ["/usr/bin/apt update", "&& /usr/bin/apt install apt-utils -y", "&& /usr/bin/apt install socat -y", "&& /usr/bin/socat tcp-listen:3306,fork TCP:10.5.0.5:3306 &",  "echo ok", "&& /bin/catalina.sh run"]
#ENTRYPOINT ["apt","update","&&","apt","install","apt-utils","-y","&&","apt","install","socat","-y","&&","socat","tcp-listen:3306,fork","TCP:10.5.0.5:3306","&", "echo","ok","&& catalina.sh","run"]