/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2019-08-20 16:15:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class template_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html  ng-app=\"app\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\" />\r\n");
      out.write("\t<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
      out.write("\t<meta http-equiv=\"Expires\" content=\"0\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"max-age=0\" />\r\n");
      out.write("\t<meta http-equiv=\"cache-control\" content=\"no-cache\" />\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"0\" />\r\n");
      out.write("\t<meta http-equiv=\"expires\" content=\"Tue, 01 Jan 1980 1:00:00 GMT\" />\r\n");
      out.write("\t<meta http-equiv=\"pragma\" content=\"no-cache\" />\t\r\n");
      out.write("\t\r\n");
      out.write("\t<meta http-equiv=\"Cache-control\" content=\"public\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-control\" content=\"private\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-control\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"Cache-control\" content=\"no-store\">\r\n");
      out.write("\t\r\n");
      out.write("\t<title>Pizza Wale</title>\r\n");
      out.write("\t<!-- link rel=\"stylesheet\" href=\"static/bootstrap/bootstrap.min.css\"-->\r\n");
      out.write("        <!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"> -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"static/bootstrap/bootstrap.min.css\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"static/images/favicon.ico\"/>\r\n");
      out.write("\t<!-- script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js\"></script-->\r\n");
      out.write("\t<!--  script src=\"static/bootstrap/bootstrap.min.js\"></script-->\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\tbody\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tbackground-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,.1)), url(static/images/pizza_background.jpg);\r\n");
      out.write("\t\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\t\tbackground-size: cover;\r\n");
      out.write("\t\t\tbackground-position: center;\r\n");
      out.write("\t\t\tbackground-attachment: fixed;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.logo\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tmargin-top:-15px;\r\n");
      out.write("\t\t\tmargin-bottom:-15px;\r\n");
      out.write("\t\t\twidth:45px;\r\n");
      out.write("\t\t\theight:45px;\r\n");
      out.write("\t\t\tfloat:left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div style=\"display:none;z-index:-999;background-image: linear-gradient(rgba(0,0,0,.3),rgba(0,0,0,.6)), url(static/images/pizza_background.jpg);background-repeat: no-repeat;background-size: cover;height:100%;  position: fixed; width:110%;background-position: center;background-attachment: fixed;height: 100%;\"></div>\r\n");
      out.write("\t<div style=\".\">\r\n");
      out.write("\t<div style=\"float:left;display:none;]\">\r\n");
      out.write("\t\t<img  src=\"static/images/logo.png\" class=\"logo\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"float: right;display:none;\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li ng-show=\"$localStorage.email\"><a href=\"#/end\">Logout</a></li>\r\n");
      out.write("\t\t\t<li ng-hide=\"$localStorage.email\"><a href=\"#/login\">Login</a></li>\r\n");
      out.write("\t\t\t<li ng-hide=\"$localStorage.email\"><a href=\"#/register\">Register</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#/\">Home</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" style=\"margin:0px;\" role=\"navigation\" ng-controller=\"NavBarController\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#exampleNavComponents\" aria-expanded\"false\">\r\n");
      out.write("                <i class=\"glyphicon glyphicon-align-center\" style=color:grey;></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <a href=\"#/\" class=\"navbar-brand\">\r\n");
      out.write("               <img  src=\"static/images/favicon.ico\" class=\"logo\">&nbsp;&nbsp;&nbsp;\r\n");
      out.write("               Pizza Wale\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"exampleNavComponents\" style=\"display:;\" >\r\n");
      out.write("            <!-- Navbar Menu -->\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                <li class=\"\" id=\"home_li\"><a class=\"homered\" href=\"#/home\">HOME</a></li>\r\n");
      out.write("                <li ng-show=\"checkLoggedIn()\" id=\"order_li\"><a class=\"homeblack\" href=\"#/order\">ORDER</a></li>\r\n");
      out.write("                <li id=\"aboutus_li\"><a class=\"homeblack\" href=\"#/aboutus\">CONTACT US</a></li>\r\n");
      out.write("                <li ng-hide=\"checkLoggedIn()\" id=\"register_li\"><a class=\"homeblack\" href=\"#/register\">REGISTER</a></li>\t\t\t\t\r\n");
      out.write("                <li ng-hide=\"checkLoggedIn()\" id=\"login_li\"><a class=\"homegreen\" href=\"#/login\">LOGIN</a>\r\n");
      out.write("                <li ng-show=\"checkLoggedIn()\" id=\"logout_li\"><a class=\"homegreen\" href=\"#/logout\">LOGOUT</a>\r\n");
      out.write("                <li ng-show=\"checkLoggedIn()\" id=\"username_li\"><a class=\"homegreen\" href=\"#\">Welcome, {{getUserName()}}</a>\r\n");
      out.write("                </li>             \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("\t<!-- render view dynamically -->\r\n");
      out.write("\t<div ng-view>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Include JS files -->\r\n");
      out.write("        <!-- Include angular -->\r\n");
      out.write("        <script src=\"static/js/angular.js\"></script>\r\n");
      out.write("        <script src=\"static/js/angular-route.js\"></script>\r\n");
      out.write("        <script src=\"static/js/angular-cookies.js\"></script>\r\n");
      out.write("        <script src=\"static/js/angular-animate.js\"></script>\r\n");
      out.write("        <script src=\"static/js/ngStorage.min.js\"></script>\r\n");
      out.write("        <!-- Include routing scripts -->\r\n");
      out.write("        <script src=\"static/js/app.js\"></script>\r\n");
      out.write("        <!-- Include services -->\r\n");
      out.write("        <script src=\"static/app-services/order.service.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"static/app-services/user.service.js\"></script>\r\n");
      out.write("        <!-- Include angular controller scripts -->\r\n");
      out.write("        <script src=\"static/home/home.controller.js\"></script>\r\n");
      out.write("        <script src=\"static/login/login.controller.js\"></script>\r\n");
      out.write("        <script src=\"static/register/register.controller.js\"></script>\r\n");
      out.write("         <script src=\"static/order/order.controller.js\"></script>\r\n");
      out.write("         <script src=\"static/editorder/editorder.controller.js\"></script>\r\n");
      out.write("         <script src=\"static/logout/logout.controller.js\"></script>\r\n");
      out.write("           <script src=\"static/aboutus/aboutus.controller.js\"></script>\r\n");
      out.write("           <script src=\"static/employee/employee.controller.js\"></script>\r\n");
      out.write("           <script src=\"static/admin/admin.controller.js\"></script>\r\n");
      out.write("         <!-- <script src=\"static/end/end.controller.js\"></script> -->\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("         app\r\n");
      out.write("         .controller('MainCtrl',function($scope, $localStorage) {\r\n");
      out.write("        \t var vm = function(){\r\n");
      out.write("        \t\t if($localStorage.email){return true;}\r\n");
      out.write("        \t\t else { return; }\r\n");
      out.write("        \t\t \r\n");
      out.write("        \t }\r\n");
      out.write("         });\r\n");
      out.write("         </script>\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("         \r\n");
      out.write("         app\r\n");
      out.write("     \t.controller('NavBarController', NavBarController);\r\n");
      out.write("\r\n");
      out.write("         NavBarController.$inject = ['$scope', '$location', 'UserService','$localStorage'];\r\n");
      out.write("\t\t\tfunction NavBarController($scope, $location, UserService,$localStorage) {\r\n");
      out.write("             console.log(\"inside NavBarController\");\r\n");
      out.write("             /*$scope.checkLoggedIn = function(){\r\n");
      out.write("             \tif($localStorage.email!=null){\r\n");
      out.write("             \t\treturn true;\r\n");
      out.write("             \t}\r\n");
      out.write("             \telse{\r\n");
      out.write("             \t\treturn false;\r\n");
      out.write("             \t}\r\n");
      out.write("         \t};*/\r\n");
      out.write("         \t$scope.checkLoggedIn=function() {\r\n");
      out.write("         \t\tconsole.log(\"inside checkLoggedIn()\");\r\n");
      out.write("     \t\t\tif($localStorage.email!=null){\r\n");
      out.write("             \t\tif($localStorage.email!=null)\r\n");
      out.write("             \t\t\t{\r\n");
      out.write("             \t\t\treturn true;\r\n");
      out.write("             \t\t\t}\r\n");
      out.write("             \t\telse return false;\r\n");
      out.write("             \t\t\r\n");
      out.write("             \t}\r\n");
      out.write("             \telse{\r\n");
      out.write("             \t\treturn false;\r\n");
      out.write("             \t}\r\n");
      out.write("     \t\t};\r\n");
      out.write("         \tfunction checkLogin()\r\n");
      out.write("         \t{\r\n");
      out.write("\r\n");
      out.write("             \t$scope.checkLoggedIn=function() {\r\n");
      out.write("             \t\tconsole.log(\"inside checkLoggedIn()\");\r\n");
      out.write("         \t\t\tif($localStorage!=null){\r\n");
      out.write("                 \t\tif($localStorage.email!=null)\r\n");
      out.write("                 \t\t\t{\r\n");
      out.write("                 \t\t\treturn true;\r\n");
      out.write("                 \t\t\t}\r\n");
      out.write("                 \t\telse return false;\r\n");
      out.write("                 \t\t\r\n");
      out.write("                 \t}\r\n");
      out.write("                 \telse{\r\n");
      out.write("                 \t\treturn false;\r\n");
      out.write("                 \t}\r\n");
      out.write("         \t\t};\r\n");
      out.write("         \t}\r\n");
      out.write("     \t\t$scope.getUserName=function()\r\n");
      out.write("        \t{\r\n");
      out.write("        \t\tconsole.log(\"$localStorage.userName:-\"+$localStorage.userName);\r\n");
      out.write("        \t\tif($localStorage!=null)\r\n");
      out.write("        \t\t\t{\r\n");
      out.write("        \t\t\t\tif($localStorage.userName!=null)\r\n");
      out.write("        \t\t\t\t\t{\r\n");
      out.write("        \t\t\t\t\treturn $localStorage.userName;\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t\telse\r\n");
      out.write("        \t\t\t\t\t{\r\n");
      out.write("        \t\t\t\t\t\treturn \"\";\r\n");
      out.write("        \t\t\t\t\t}\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\telse\r\n");
      out.write("        \t\t\t{\r\n");
      out.write("        \t\t\t\treturn \"Guest\";\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t}\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\t/* (function checkLoggedIn() {\r\n");
      out.write("     \t\t\tif($localStorage.email!=null){\r\n");
      out.write("             \t\treturn true;\r\n");
      out.write("             \t}\r\n");
      out.write("             \telse{\r\n");
      out.write("             \t\treturn false;\r\n");
      out.write("             \t}\r\n");
      out.write("     \t\t}\r\n");
      out.write("     \t\t)(); */\r\n");
      out.write("         \t\r\n");
      out.write("     \t}\r\n");
      out.write("         </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
